### ISSUE TITLE
FlipWifi erroring when trying to scan

### ISSUE THREAD

**Issue by Dividfoxx** [jblanked/FlipWiFi#2]
Hey, 
I’ve flashed FlipperHTTP to my Wifi Developer Board but every time I try to scan on FlipWifi it works for maybe a second then gives me an error saying that it failed to scan.
I’ve reflashed the board, reinstalled the app and rebooted the flipper but nothing seems to be working. 
I’m not really sure what to do now.

**Comment by jblanked** [comment]
Hey, which version of FlipWiFi are you using? Download the latest from the store and report back please.

**Comment by Dividfoxx** [comment]
Hey, I just downloaded the latest version off the store and it hasn’t changed anything unfortunately

**Comment by Dividfoxx** [comment]
Version 1.2 btw

**Comment by jblanked** [comment]
Let's troubleshoot further. 

Here's a few solutions: https://github.com/jblanked/FlipperHTTP/blob/main/HELP.md

I also recommend saving your WiFi credentials manually (in the Saved APs menu). You can also do this within each of the FlipperHTTP apps. 

Give FlipLibrary or FlipWeather a try 🔥

**Comment by Zaphodbartfast** [comment]
Hi there.
I've got a similar problem. I've got the flipper developer board with a ESP32-S2-WROVER.
Couldn't find this specific one so I installed the devboard ESP32-S2. witch seemed to work(after a couple of crashes). Installation worked fine but as soon I tried to connect to the WiFi via flip Wifi (v 1.2) and scan, it just tells me "Wi-Fi Nearby and that's it. Then I tried to connect manually to my Wi-Fi. Witch seemed to work. Got a the [SUCCESS] message, but when I tried one of the flip apps like weather/social etc. I get the message [ERROR] Not connected to the Wi-Fi/ update your Wi-Fi settings. 
I am really new to flipper and github, so please be patient with me.

**Comment by jblanked** [comment]
Hey,

If you're using the Official Developer Board then use the .bin files for the Developer Board. 

If you only see "WiFi Nearby" in FlipWiFi, that means it was unable to find networks nearby. 

For the Not connected to WiFi message, check out solutions here:  https://github.com/jblanked/FlipperHTTP/blob/main/HELP.md

**Comment by Zaphodbartfast** [comment]
hey, thanks for the quick answer.

I did perform a cold boot, force the bootloader mode but did not receive any message. but i continued by exiting to main menu of the esp flasher app. disconnect and reconnect my board (did get 3x green led flashes). enter the bootloader and flashed manual. 
by trying to enter manual over flip wifi, flipper crashes. by trying the scan it tells me to use the latest http software.

i can not make sence out of "update your wifi credentials (well, that makes sence to me but) in the settings menu option of each app (except FlipWiFi).??

i have checked my SSID and passwort where i could. 
my wifi is at 2.4 ghz. 

it does blink when i enter apps or move around in the menu but thats it.

maybe i messed up some menu settings. 

i checked the UART Terminal but nothing there.

my menu settings are: Log Level <Debug>
                                     Log Level  USART>
                                     Log B Rate 57600
                                     Debug     <on    (also tried off, no differece)
                                     Heap Trace <Main
                                     Sleep Method <Legacy
                                    (hope those infos are helping)

big thanks for your time and help.

**Comment by jblanked** [comment]
Thank you for your patience and detailed description of the issues you're facing and your configuration settings.

Let's troubleshoot further.

Since you saw the three green LED flashes when flashing and a LED blink when entering the apps, that confirms you have flashed correctly and have used the correct flash for your board.

When you use the other FlipperHTTP apps, are you able to utilize their functionalities? (Access Weather/GPS in FlipWeather, get a random fact form FlipLibrary, register on FlipSocial, etc)

**Comment by Zaphodbartfast** [comment]
Right now I just get the http error. That tells me to connect and get the latest firmware. 

But these apps tried to get information at one point, but then told me that there is no wifi connection. 

Strange is it that it tells me that the board is not connected or don't got the latest firmware on, but then tries to catch weather data until it tells me error not connected to the WiFi.

**Comment by Zaphodbartfast** [comment]
And no. I did not get any data from any wifi app.

**Comment by jblanked** [comment]
Awesome! Let's stick with FlipWeather to troubleshoot. Ensure that the WiFi you're connecting to is not a 5 GHz network. Sometimes if two networks have the same name, it can be confusing. In FlipWeather's settings, update your credentials again (to a 2.4 GHz network) and report back.

**Comment by jblanked** [comment]
That's definitely a step forward; typos can cause confusion for sure. 

If you were able to use FlipWeather, even once, that confirms that your board is working correctly and is able to connect to your WiFi. Are you using the latest version of the FlipperHTTP apps? You can download them from lab.flipper.net or www.flipsocial.net/download

I will look into FlipWiFi crashing when saving manually. For now, let's focus on making sure you're connected and can utilize the other apps. 

You can try:
- saving and updating your WiFi credentials (make sure to wait until the LED stops flashing before continuing)
- disconnecting your board, restarting your flipper, then saving and updating your credentials

Usually that does the trick, if not, we should look into your connection between the board and the flipper (using Dupont wires, directly plugging it into your flipper, if you're using a case, etc)

**Comment by Zaphodbartfast** [comment]
It should be the latest versions of the HTTP Apps. I downloaded them over the mobile phone App. Should I delete them and install them via q flipper? 
I've tried the saving and updating your WiFi credentials (make sure to wait until the LED stops flashing before continuing) 

No led flashes at all.

disconnecting your board, restarting your flipper, then saving and updating your credentials. Did that to but still no connection to the WiFi.

**Comment by Zaphodbartfast** [comment]
I do have a silicone case for the flipper and a hard plastic case for the board and this is directly connected to the GPIO of the flipper. Now I took both cases of. Still the same.

**Comment by jblanked** [comment]
Hmm if the LED did not flash at all while saving, then I suggest re-flashing. If you bought the official WiFi dev board from the official store, use https://github.com/jblanked/FlipperHTTP/tree/main/WiFi%20Developer%20Board%20(ESP32S2)

If you are using an ESP-32-WROOVER (like you mentioned) but it's not from the store/amazon, then use https://github.com/jblanked/FlipperHTTP/tree/main/ESP32-WROVER

Post Edit: Try turning off DEBUG (I don't think this will make a difference but if does I will update the HELP.md)

**Comment by Zaphodbartfast** [comment]
Well. To be honest I'm not quite sure witch board I got. It looks like the original one (Flipper Zero WiFi Module v1 printed on it) except for the ESP32-S2-WROVER modul that sits on it. I'll try to take some pictures, just to be sure. Cause I think this might be the problem.

**Comment by Zaphodbartfast** [comment]
![Uploading Screenshot_20241205-175933_Gallery.jpg…]()

**Comment by Zaphodbartfast** [comment]
Don't know if that uploading from those screenshots worked....

**Comment by jblanked** [comment]
I’m unable to see the screenshots.

**Comment by Zaphodbartfast** [comment]
Ok. I will try to find a link to a similar one. https://www.amazon.com/WiFi-Devboard-Flipper-Firmware-Accessories/dp/B0D9YB1NBV

**Comment by Zaphodbartfast** [comment]
Tried every app with DEBUG OFF. every app crashed.

**Comment by Zaphodbartfast** [comment]
With DEBUG ON they are not crashing and they start fetching data(green led constantly on). Until the message "not connected to WiFi" or, witch is new, "Unusual error" on flip trade app.

**Comment by jblanked** [comment]
Hmm, so switching DEBUG from OFF to ON made your board start working again? That's odd. Try saving your WiFi credentials again.

**Comment by Zaphodbartfast** [comment]
Well... now it is just crashing again, in every app. Even when I turned DEBUG OFF and ON. Really odd... 

Should I try to re-flash the board?

**Comment by jblanked** [comment]
Hmm yeah that's very odd. There must be another issue if it works and then all of a sudden doesn't work. You could try refreshing. Also, your GPS and Weather information are based on your IP Address, so it's not _exactly_ where you location is.

**Comment by Zaphodbartfast** [comment]
Could you make out the correct "flashware" for my board? Maybe there is the problem... 
Should I flash via flipper esp flasher?

**Comment by jblanked** [comment]
Yes you should flash via the ESP Flasher app. And the correct files for your board are in https://github.com/jblanked/FlipperHTTP/tree/main/WiFi%20Developer%20Board%20(ESP32S2)

**Comment by Zaphodbartfast** [comment]
So I did. I can get almost every app running (with resetting the board and refreshing SSID and password, every time). Not really stable (crashes sometimes, note: Null pointer dereference) but I can do things (found you flip social..). The only app that is just crashing is the flip Wifi.

**Comment by Zaphodbartfast** [comment]
I also have now a green light when I save the SSID.

**Comment by jblanked** [comment]
Awesome that's much better. I'll update the HELP.md with some of the things we discussed and will update FlipWiFi. Thank you!

**Comment by jblanked** [comment]
Re opening in case others have this issue. I fixed the crash that occurred when setting/saving the networks. It will be released in version 1.2.1.

**Comment by jblanked** [comment]
FlipWiFi version 1.2.1 just got released. This update fixes the crash that occurred when setting the network.
